CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS subscribers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(160) NOT NULL,
    phone_number VARCHAR(40) UNIQUE NOT NULL,
    address VARCHAR(255) NOT NULL,
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS services (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) UNIQUE NOT NULL,
    monthly_price NUMERIC(10, 2) NOT NULL CHECK (monthly_price >= 0)
);

CREATE TABLE IF NOT EXISTS subscriber_services (
    subscriber_id INTEGER NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    service_id INTEGER NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    PRIMARY KEY (subscriber_id, service_id)
);

CREATE TABLE IF NOT EXISTS invoices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id INTEGER NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    amount NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
    description TEXT NOT NULL,
    is_paid BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users(username, password)
VALUES ('admin', 'admin123')
ON CONFLICT (username) DO NOTHING;

INSERT INTO services(name, monthly_price)
VALUES
    ('Міські дзвінки', 120.00),
    ('Міжнародні дзвінки', 250.00),
    ('Голосова пошта', 60.00),
    ('Інтернет-пакет', 180.00)
ON CONFLICT (name) DO NOTHING;
